### ISSUE TITLE
Deliverables

### ISSUE THREAD

**Issue by tharvey5** [CS1C-BitB/ModelBois#23]
@ChrisJAllan Gimme until about 9, the sprint back log and the product back log are taking longer than I thought

Also is the following done: 
4) text file documenting which source files, line numbers from step 3) satisfy individual project requirements (#1 thru #10) and general project requirements (second paragraph of assignment). For each project requirement include source file .h, .cpp name and relevant line numbers.

or do you need me to do that? No worries either way I just need to know so I can get that too you

**Comment by tharvey5** [comment]
[Deliverables.zip](https://github.com/CS1C-BitB/ModelBois/files/2655812/Deliverables.zip)

**Comment by tharvey5** [comment]
Here's the bulk, I am gonna do a member contribution form real quick

**Comment by tharvey5** [comment]
[Deliverables.zip](https://github.com/CS1C-BitB/ModelBois/files/2655835/Deliverables.zip)

**Comment by tharvey5** [comment]
@ChrisJAllan The following .zip contains

1. Doxygen documentation - as a zip inside as well
2. Daily Scrum log
3. Sprint Log
4. Product Backlog
5. Member contribution form

**Comment by tharvey5** [comment]
That will cover #5, 6, 8 in the part of the deliverables.

Your more than welcome to include more information under your name for the contribution sheet. Its not required but he asked me if we would include it at minimum to indicate the members who actually contributed to the project

**Comment by tharvey5** [comment]
Lemme know if you need anything else, I will continue to check back

**Comment by ChrisJAllan** [comment]
Okay, and will someone else be submitting the UML diagrams?

**Comment by tharvey5** [comment]
@ChrisJAllan yes I am doing that
