### ISSUE TITLE
Reading Files in QT

### ISSUE THREAD

**Issue by tharvey5** [CS1C-BitB/ModelBois#3]
Is reading files in QT different from like Visual Studio Code or Eclipse?? When I do the basic stuff using the standard library stuff it is not working, rather not doing anything

**Comment by tharvey5** [comment]
@ChrisJAllan

**Comment by ChrisJAllan** [comment]
The file you want to read needs to be in the build directory, not the source. Make sure the file is in the same folder as the executable, or the one shown on this page: ![this page](https://user-images.githubusercontent.com/9275775/48179558-9e34ba80-e2d4-11e8-812b-c9adfe47fdef.png)

**Comment by tharvey5** [comment]
Alright, will check that out! I appreciate the help man!
