### ISSUE TITLE
Input File

### ISSUE THREAD

**Issue by tharvey5** [CS1C-BitB/ModelBois#5]
@ChrisJAllan Hey I am really lost with reading in this input file in terms of how to make it work for our project. I tried a few different things yesterday and spent a few hours on it but none would work for what we need it for. I could use some help / guidance on how it should properly be done whenever you get a chance

**Comment by ChrisJAllan** [comment]
How I would this is to make an enum of all the file's fields (ShapeId, ShapeType, etc.) and make a string-to-enum map (beause C++ can't switch over strings, convert to an enum first then switch). To handle the case where ShapeType is given after ShapeDimensions, I would read the whole ShapeDimensions value into a string with `getline` and then parse it after all the data for that shape has been loaded (when the parser reaches an empty line).

**Comment by ChrisJAllan** [comment]
As part of the property editor, I am making string to value converters that might be helpful here.

https://github.com/CS1C-BitB/ModelBois/blob/0ef76dce3dc60b0c16f76ddb734b5724adcf8773/src/Shape.h#L21

Using it is simply `Qt::BrushStyle style = BRUSH_STYLE_NAMES.key(string, default_style);`
I'll be making similar things for the pen styles later, probably tomorrow.
