### ISSUE TITLE
CheckPoint 2

### ISSUE THREAD

**Issue by tharvey5** [CS1C-BitB/ModelBois#7]
@ChrisJAllan hey so Nicole is doing the daily reports for the shapes and I am gonna do the UI to add the shapes. Would you be able to write the save file? The file parser works, theres a couple things I am gonna try to work out on my end but so far so good. Have a good weekend

**Comment by tharvey5** [comment]
Detailed reports*

**Comment by ChrisJAllan** [comment]
Alright, can do

**Comment by ChrisJAllan** [comment]
@tharvey5 I noticed that the build files were being included in your commits. I've updated the .gitignore file so that this does not happen anymore, make sure to fetch and then rebase against `origin/master`, then run the following to remove the files from the repo:
```
git rm -r --cached .
git add .
```

**Comment by tharvey5** [comment]
@ChrisJAllan will do and we are trying to meet as a group around 1230 tomorrow to see what's done and kinda go over the next steps to gets this project finished.

**Comment by tharvey5** [comment]
In the lab, does that work for you or is there a time conflict?

**Comment by ChrisJAllan** [comment]
That's fine. I've got a class at 2, so I can spare an hour or so.

Also, since rebasing everything was gonna be messy, I cleaned it up in a new branch [here](https://github.com/CS1C-BitB/ModelBois/tree/ShapeFile-Rebased) with all the changes updated against the new code. If you have any further changes to make, I would suggest putting them there.

**Comment by tharvey5** [comment]
[BoysInTheBack.png.zip](https://github.com/CS1C-BitB/ModelBois/files/2646952/BoysInTheBack.png.zip)

**Comment by tharvey5** [comment]
@ChrisJAllan I posted the logo above

**Comment by tharvey5** [comment]
@ChrisJAllan Lemme know when its pretty much all good to go so I can comment whatever else is needed and run it through Doxygen

**Comment by ChrisJAllan** [comment]
Are you going to do any more on the file loading and login screen or should I take what's already there?  Currently that and the About screen are all that's left.

**Comment by tharvey5** [comment]
@ChrisJAllan Go ahead and just work your magic, if you need me to fix something on the file loading lemme know otherwise do what you need to do

**Comment by tharvey5** [comment]
The detailed reports work great and ya the login in was obviously very basic I dunno how you want to implement that but you would know better than I

**Comment by ChrisJAllan** [comment]
Everything is done, document away

**Comment by tharvey5** [comment]
@ChrisJAllan Will do!
